# Generated by Django 4.1.1 on 2022-10-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_userfollows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.DeleteModel(name="Photo",),
    ]
