# Generated by Django 4.1.1 on 2022-09-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="profile_photo",),
    ]
