# Generated by Django 4.1.1 on 2022-09-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="follows",),
    ]
